services:
  frontend:
    build:
      context: .
      dockerfile: dev.Dockerfile
      args:
        VITE_BACKEND_URL: http://host.docker.internal:3000
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5173:5173"
    environment:
      NODE_ENV: development
      VITE_BACKEND_URL: http://host.docker.internal:3000
    command: npm run dev -- --host
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy-front
    depends_on:
      - frontend