services:
  mongo:
    image: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes: 
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db

  redis:
    image: redis
    ports:
      - 6379:6379
    environment:
      REDIS_URL: redis://redis:6379/0
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - ./todo-backend/redis_data:/data
  
  frontend:
    image: todo-frontend
    build:
      context: ./todo-frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./todo-frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: development
      VITE_BACKEND_URL: http://localhost:8080/api
    command: npm run dev -- --host

  backend:
    image: todo-backend
    build:
      context: ./todo-backend
      dockerfile: dev.Dockerfile
    environment:
      NODE_ENV: development
      MONGO_URL: mongodb://root:example@mongo:27017/the_database
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - mongo
      - redis
    volumes:
      - ./todo-backend:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - backend
      - frontend

volumes:
  mongo_data:
  redis_data:
